apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-prot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt-prot
  template:
    metadata:
      labels:
        app: chatgpt-prot
    spec:
      containers:
        - name: chatgpt-prot
          image: chatgpt_prot
          imagePullPolicy: Never
          ports:
            - containerPort: 5500

---
apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  type: NodePort
  selector:
    app: chatgpt-prot
  ports:
    - port: 80
      targetPort: 5500
      nodePort: 30000
